# name: Trigger Netlify Build
# on:
#   schedule:
#     - cron: '0 0 * * *'
# jobs:
#   build:
#     name: Request Netlify Webhook
#     runs-on: ubuntu-latest
#     steps:
#       - name: Curl request
#         run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e0bd31f58d42ce0cc4d888c
